[package]

name = "lifelike"
version = "0.0.1"
authors = [ "Jeff Parsons <jeff@parsons.io>" ]

[[bin]]

name = "lifelike"

[dependencies]

getopts = "0.2.1"

[dependencies.png]

git = "https://github.com/servo/rust-png.git"
